// Redirect
export const SET_REDIRECT = 'SET_REDIRECT'
export const RESET_REDIRECT = 'RESET_REDIRECT'

// RequestStatus
export const SET_REQUEST_NOT_STARTED = 'SET_REQUEST_NOT_STARTED'
export const SET_REQUEST_PENDING = 'SET_REQUEST_PENDING'
export const SET_REQUEST_SUCCESS = 'SET_REQUEST_SUCCESS'
export const SET_REQUEST_FAILURE = 'SET_REQUEST_FAILURE'

// Toast
export const DISPLAY_TOAST = 'DISPLAY_TOAST'
